### ISSUE TITLE
Update from v4 never worked, including 5.2.1~ynh8

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/cryptpad_ynh#193]
Hi!

Yunohost 11.1.18
Update from Cryptpad 4.12.0\~ynh2 to 5.2.1\~ynh6 had an CORS issue with the sandbox domain, as the target url was in 404 error
Update from 5.2.1\~ynh6 to 5.2.1\~ynh8 has another issue: Cryptad logo stay still, as "the ressource has been blocked because of an incorrect MIME type" and obviously, the Cryptad service is down, see the log below.

```
-- Journal begins at Wed 2022-10-26 10:26:11 CEST, ends at Mon 2023-04-17 20:41:18 CEST. --
avril 17 20:41:11 systemd[1]: Stopped CryptPad: Zero Knowledge realtime collaborative editor..
avril 17 20:41:11 systemd[1]: Started CryptPad: Zero Knowledge realtime collaborative editor..
avril 17 20:41:12 npm[2836583]: npm does not support Node.js v8.17.0
avril 17 20:41:12 npm[2836583]: You should probably upgrade to a newer version of node as we
avril 17 20:41:12 npm[2836583]: can't make any promises that npm will work with this version.
avril 17 20:41:12 npm[2836583]: You can find the latest version at https://nodejs.org/
avril 17 20:41:12 npm[2836583]: /opt/node_n/n/versions/node/16.14.2/lib/node_modules/npm/lib/npm.js:32
avril 17 20:41:12 npm[2836583]:   #unloaded = false
avril 17 20:41:12 npm[2836583]:   ^
avril 17 20:41:12 npm[2836583]: SyntaxError: Invalid or unexpected token
avril 17 20:41:12 npm[2836583]:     at createScript (vm.js:80:10)
avril 17 20:41:12 npm[2836583]:     at Object.runInThisContext (vm.js:139:10)
avril 17 20:41:12 npm[2836583]:     at Module._compile (module.js:617:28)
avril 17 20:41:12 npm[2836583]:     at Object.Module._extensions..js (module.js:664:10)
avril 17 20:41:12 npm[2836583]:     at Module.load (module.js:566:32)
avril 17 20:41:12 npm[2836583]:     at tryModuleLoad (module.js:506:12)
avril 17 20:41:12 npm[2836583]:     at Function.Module._load (module.js:498:3)
avril 17 20:41:12 npm[2836583]:     at Module.require (module.js:597:17)
avril 17 20:41:12 npm[2836583]:     at require (internal/module.js:11:18)
avril 17 20:41:12 npm[2836583]:     at module.exports (/opt/node_n/n/versions/node/16.14.2/lib/node_modules/npm/lib/cli.js:22:15)
avril 17 20:41:12 systemd[1]: cryptpad.service: Main process exited, code=exited, status=1/FAILURE
avril 17 20:41:12 systemd[1]: cryptpad.service: Failed with result 'exit-code'.
avril 17 20:41:12 systemd[1]: cryptpad.service: Scheduled restart job, restart counter is at 4.
avril 17 20:41:12 systemd[1]: Stopped CryptPad: Zero Knowledge realtime collaborative editor..
avril 17 20:41:12 systemd[1]: Started CryptPad: Zero Knowledge realtime collaborative editor..
avril 17 20:41:12 npm[2836591]: npm does not support Node.js v8.17.0
avril 17 20:41:12 npm[2836591]: You should probably upgrade to a newer version of node as we
avril 17 20:41:12 npm[2836591]: can't make any promises that npm will work with this version.
avril 17 20:41:12 npm[2836591]: You can find the latest version at https://nodejs.org/
avril 17 20:41:12 npm[2836591]: /opt/node_n/n/versions/node/16.14.2/lib/node_modules/npm/lib/npm.js:32
avril 17 20:41:12 npm[2836591]:   #unloaded = false
avril 17 20:41:12 npm[2836591]:   ^
avril 17 20:41:12 npm[2836591]: SyntaxError: Invalid or unexpected token
avril 17 20:41:12 npm[2836591]:     at createScript (vm.js:80:10)
avril 17 20:41:12 npm[2836591]:     at Object.runInThisContext (vm.js:139:10)
avril 17 20:41:12 npm[2836591]:     at Module._compile (module.js:617:28)
avril 17 20:41:12 npm[2836591]:     at Object.Module._extensions..js (module.js:664:10)
avril 17 20:41:12 npm[2836591]:     at Module.load (module.js:566:32)
avril 17 20:41:12 npm[2836591]:     at tryModuleLoad (module.js:506:12)
avril 17 20:41:12 npm[2836591]:     at Function.Module._load (module.js:498:3)
avril 17 20:41:12 npm[2836591]:     at Module.require (module.js:597:17)
avril 17 20:41:12 npm[2836591]:     at require (internal/module.js:11:18)
avril 17 20:41:12 npm[2836591]:     at module.exports (/opt/node_n/n/versions/node/16.14.2/lib/node_modules/npm/lib/cli.js:22:15)
avril 17 20:41:12 systemd[1]: cryptpad.service: Main process exited, code=exited, status=1/FAILURE
avril 17 20:41:12 systemd[1]: cryptpad.service: Failed with result 'exit-code'.
avril 17 20:41:12 systemd[1]: cryptpad.service: Scheduled restart job, restart counter is at 5.
avril 17 20:41:12 systemd[1]: Stopped CryptPad: Zero Knowledge realtime collaborative editor..
avril 17 20:41:12 systemd[1]: cryptpad.service: Start request repeated too quickly.
avril 17 20:41:12 systemd[1]: cryptpad.service: Failed with result 'exit-code'.
avril 17 20:41:12 systemd[1]: Failed to start CryptPad: Zero Knowledge realtime collaborative editor..
```

seems to be a Node.js error? Thanks !

**Comment by ericgaspar** [comment]
Closing. The package changed a lot. Please reopen an issue if needed.
